#!/bin/bash

# Source the functions from functions.sh
source "$SCRIPT_DIR/utils/functions.sh"

# EDIT: Define the script, its path and arguments
script_name="copy_files"
script_path="$SCRIPT_DIR"
script_args=""
log_name="STEP12_copy_files"  # If blank, the log name will be the script name
mode="bg" # Default mode is background

script_code() {
  echo "Running..."
  ############################################
  ## Put the script specific code here
  ## This executes in the project directory ##
  ############################################

  # Define the paths
  SCRATCH_PATH="$SCRATCH_ROOT/$project_name"
  PROJECT_PATH=$project_path

  # Set the directories
  dirs="clouds,downsample,figures,fsct,models,rxp2ply"

  # Tell the use what we are doing
  echo "Copying files in directories $dirs from $SCRATCH_PATH to $PROJECT_PATH"
  echo "This will run in the background"
  echo ""

  # Compose the script arguments

  script_args="--project_path $PROJECT_PATH --scratch_path $SCRATCH_PATH --dirs $dirs"

  ############################################
  ## End of the script specific code here   ##
  ############################################
}

# Call the functions defined in functions.sh
# This needs to be in the right order.
parse_arguments "$@"
check_project_name
check_projects_file
change_directory
script_code
generate_command
run_command
