#!/bin/bash
#
# Downsample the PLY files

# Source the functions from functions.sh
source "$SCRIPT_DIR/utils/functions.sh"

# EDIT: Define the script, its path and arguments
script_name="downsample.py"
script_path="$SCRIPT_DIR/python"
script_args="" # see below
log_name="STEP02_downsample_ply_files"  # If blank, the log name will be the script name
mode="bg" # Default mode is background

script_code() {
  echo "Running..."
  ############################################
  ## Put the script specific code here
  ## This executes in the project directory ##
  ############################################

  # Activate the conda environment
  conda activate pdal

  # Define the directories
  downsample_dir="$SCRATCH_ROOT/$project_name/downsample"
  rxp2ply_dir="$SCRATCH_ROOT/$project_name/rxp2ply"

    # Identify the log_file
    # If the log name is not provided, use the script name
  if [ -z "$log_name" ]; then
    log_file="$LOG_ROOT/$project_name/$(basename $script_name).log"
  else
    log_file="$LOG_ROOT/$project_name/$log_name.log"
  fi


   # Compose the script arguments
  script_args="--idir $rxp2ply_dir --odir $downsample_dir --length .02 --verbose --log-file $log_file --num-prcs 2"

  ############################################
  ## End of the script specific code here   ##
  ############################################
}

# Call the functions defined in functions.sh
# This needs to be in the right order.
parse_arguments "$@"
check_project_name
check_projects_file
change_directory
script_code
generate_command
run_command
