#!/bin/bash
#
# Generates input parameters .m files for all trees

# Source the functions from functions.sh
source "$SCRIPT_DIR/utils/functions.sh"

# EDIT: Define the script, its path and arguments
script_name="generate_inputs.updated.py"
script_path="$SCRIPT_DIR/python"
script_args="" # see below
log_name="STEP06_generate_inputs"  # If blank, the log name will be the script name
mode="bg" # Default mode is background

script_code() {
  echo "Running..."
  ############################################
  ## Put the script specific code here
  ## This executes in the project directory ##
  ############################################

  # Activate the conda environment
  conda activate pdal

  # Define the directories
  intermediate_inputs_dir="$SCRATCH_ROOT/$project_name/models/intermediate/inputs"
  clouds_dir=$(realpath "$SCRATCH_ROOT/$project_name/clouds")

  # Move the clouds_dir/0.0 directorty to be clouds_dir/x0.0
  mv $clouds_dir/0.0 $clouds_dir/x0.0
  echo "Moved $clouds_dir/0.0 to $clouds_dir/x0.0"
  echo ""

   # Compose the script arguments
  script_args="--input_path $clouds_dir --output_path $intermediate_inputs_dir"

  ############################################
  ## End of the script specific code here   ##
  ############################################
}

# Call the functions defined in functions.sh
# This needs to be in the right order.
parse_arguments "$@"
check_project_name
check_projects_file
change_directory
script_code
generate_command
run_command
