#!/bin/bash
#
# This script is used to generate the ply files from the rxp files
# It uses the rxp2ply.py script

# Source the functions from functions.sh
source "$SCRIPT_DIR/utils/functions.sh"

# EDIT: Define the script, its path and arguments
script_name="rxp2ply.py"
script_path="$SCRIPT_DIR/python"
script_args=""
log_name="STEP01_generate_ply_files"  # If blank, the log name will be the script name
mode="bg" # Default mode is background

script_code() {
  echo "Running..."
  ############################################
  ## Put the script specific code here
  ## This executes in the project directory ##
  ############################################

  # Activate the conda environment
  conda activate pdal


  # Define the directories
  downsample_dir="$SCRATCH_ROOT/$project_name/downsample"
  raw_dir="$project_path/raw"
  rxp2ply_dir="$SCRATCH_ROOT/$project_name/rxp2ply"
  matrix_dir="$project_path/matrix"
  bounding_file="$SCRATCH_ROOT/$project_name/rxp2ply/bounding_box"

  # Identify the log_file
    # If the log name is not provided, use the script name
  if [ -z "$log_name" ]; then
    log_file="$LOG_ROOT/$project_name/$(basename $script_name).log"
  else
    log_file="$LOG_ROOT/$project_name/$log_name.log"
  fi

  # Check if project_name is lpg_01 or fg6c2
  if [ "$project_name" = "lpg_01" ]; then
    global_matrix="$project_path/2022_to_2016_rotation.dat"
  fi

   # Compose the script arguments
  script_args="--project $raw_dir --matrix-dir $matrix_dir --deviation 15 --tile 10 --odir $rxp2ply_dir --reflectance -20 5 --verbose --rotate-bbox
  --save-bounding-geometry $bounding_file --log-file $log_file --num-prcs 2"

  # Add --global-matrix if the global matrix is defined
  if [ -n "$global_matrix" ]; then
    script_args="$script_args --global-matrix $global_matrix"
  fi

  ############################################
  ## End of the script specific code here   ##
  ############################################
}

# Call the functions defined in functions.sh
# This needs to be in the right order.
parse_arguments "$@"
check_project_name
check_projects_file
change_directory
script_code
generate_command
run_command
