#!/bin/bash
#
# This script is used to run the semantic segmentation using the run_fsct_array script

# Source the functions from functions.sh
source "$SCRIPT_DIR/utils/functions.sh"

# EDIT: Define the script, its path and arguments
script_name="sbatch"
script_path="" # empty because sbatch is in the $PATH
script_args=""
log_name="STEP04_semantic_segmentation"  # If blank, the log name will be the script name
mode="bg" # Default mode is background

script_code() {
  echo "Running..."
  ############################################
  ## Put the script specific code here
  ## This executes in the project directory ##
  ############################################

  # Define the paths
  SCRATCH_DIR="$SCRATCH_ROOT/$project_name"
  PROJECT_DIR=$project_path

  downsample_dir="$SCRATCH_ROOT/$project_name/downsample"

  # Get the largest number from the file names
  file_count=$(ls "$downsample_dir" | grep -o '[0-9]\+' | sort -n | tail -n 1)

  # Remove any leading zeros in file_count
  file_count=$(echo $file_count | sed 's/^0*//')

  # Set the name of the sbatch_log_dirs which are defined in the array job #sbatch directives
  # Used by execute task to add to log file
  sbatch_log_dir="/work/scratch-pw3/ucfacc2/sbatch_logs/ss/"

  # Print the file count
  echo "Largest number in file names in $downsample_dir: $file_count"
  echo ""

  job_name="${project_name}_semantic_seg"

  # Compose the script arguments
  script_args="--array=0-$file_count --job-name $job_name --export=ALL,project_dir=$PROJECT_DIR,scratch_dir=$SCRATCH_DIR $SCRIPT_DIR/jobs/run_fsct_array"

  ############################################
  ## End of the script specific code here   ##
  ############################################
}

# Call the functions defined in functions.sh
# This needs to be in the right order.
parse_arguments "$@"
check_project_name
check_projects_file
change_directory
script_code
generate_command
run_command
