#!/bin/bash
#
# This script is used to run tests

# Source the functions from functions.sh
source "$SCRIPT_DIR/utils/functions.sh"

# EDIT: Define the script, its path and arguments
script_name="sleep"
script_path=""
script_args=""
log_name="STEP99_do_TEST_09"  # If blank, the log name will be the script name
mode="bg" # Default mode is background



script_code() {
  echo "Running..."
  ############################################
  ## Put the script specific code here
  ## This executes in the project directory ##
  ############################################

  # Compose the script arguments
  script_args=" 10"

  ############################################
  ## End of the script specific code here   ##
  ############################################
}
parse_arguments $@
check_project_name
check_projects_file
change_directory
script_code
generate_command
run_command
#done
